// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using despachoAeronave.Models;

#nullable disable

namespace despachoAeronave.Migrations
{
    [DbContext(typeof(EscuelaDatabaseContext))]
    partial class EscuelaDatabaseContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("despachoAeronave.Models.Aeronave", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CapacidadPasajeros")
                        .HasColumnType("int");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("Matricula")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Modelo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("Aeronaves");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CapacidadPasajeros = 170,
                            Estado = "Activa",
                            Matricula = "LV-CUX",
                            Modelo = "Boeing 737-800"
                        },
                        new
                        {
                            Id = 2,
                            CapacidadPasajeros = 186,
                            Estado = "Activa",
                            Matricula = "LV-FCR",
                            Modelo = "Boeing 737-800 MAX"
                        },
                        new
                        {
                            Id = 3,
                            CapacidadPasajeros = 96,
                            Estado = "Activa",
                            Matricula = "LV-GKO",
                            Modelo = "Embraer 190"
                        },
                        new
                        {
                            Id = 4,
                            CapacidadPasajeros = 272,
                            Estado = "Mantenimiento",
                            Matricula = "LV-FVL",
                            Modelo = "Airbus A330-200"
                        });
                });

            modelBuilder.Entity("despachoAeronave.Models.Despacho", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<double>("CargaPago")
                        .HasColumnType("float");

                    b.Property<string>("ClimaReporte")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("CombustibleRequerido")
                        .HasColumnType("float");

                    b.Property<string>("DespachadorNombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<string>("Observaciones")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Ruta")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("VueloId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("VueloId");

                    b.ToTable("Despachos");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CargaPago = 12500.0,
                            ClimaReporte = "SABE 010600Z 12008KT 9999 FEW030 18/14 Q1015; SACO 010600Z 09005KT 9999 SKC 15/10 Q1016",
                            CombustibleRequerido = 4500.0,
                            DespachadorNombre = "Juan Pérez (Despachador)",
                            FechaCreacion = new DateTime(2026, 6, 2, 6, 0, 0, 0, DateTimeKind.Local),
                            Observaciones = "Vuelo despachado con desvío estándar por clima favorable. Combustible incluye reserva regulada de 45 minutos.",
                            Ruta = "AEP UT312 COR",
                            VueloId = 2
                        });
                });

            modelBuilder.Entity("despachoAeronave.Models.Usuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Contrasena")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("NombreCompleto")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("NombreUsuario")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Rol")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id");

                    b.ToTable("Usuarios");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Contrasena = "admin123",
                            NombreCompleto = "Administrador del Sistema",
                            NombreUsuario = "admin",
                            Rol = "Despachador"
                        },
                        new
                        {
                            Id = 2,
                            Contrasena = "despacho123",
                            NombreCompleto = "Juan Pérez (Despachador)",
                            NombreUsuario = "despacho",
                            Rol = "Despachador"
                        },
                        new
                        {
                            Id = 3,
                            Contrasena = "piloto123",
                            NombreCompleto = "Martín Gómez (Comandante)",
                            NombreUsuario = "piloto",
                            Rol = "Piloto"
                        });
                });

            modelBuilder.Entity("despachoAeronave.Models.Vuelo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AeronaveId")
                        .HasColumnType("int");

                    b.Property<string>("Destino")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime>("FechaHoraLlegada")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaHoraSalida")
                        .HasColumnType("datetime2");

                    b.Property<string>("NumeroVuelo")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("Origen")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("AeronaveId");

                    b.ToTable("Vuelos");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AeronaveId = 4,
                            Destino = "MAD (Madrid)",
                            Estado = "Programado",
                            FechaHoraLlegada = new DateTime(2026, 6, 3, 14, 10, 0, 0, DateTimeKind.Local),
                            FechaHoraSalida = new DateTime(2026, 6, 2, 23, 55, 0, 0, DateTimeKind.Local),
                            NumeroVuelo = "AR1300",
                            Origen = "EZE (Buenos Aires)"
                        },
                        new
                        {
                            Id = 2,
                            AeronaveId = 1,
                            Destino = "COR (Córdoba)",
                            Estado = "Programado",
                            FechaHoraLlegada = new DateTime(2026, 6, 2, 9, 50, 0, 0, DateTimeKind.Local),
                            FechaHoraSalida = new DateTime(2026, 6, 2, 8, 30, 0, 0, DateTimeKind.Local),
                            NumeroVuelo = "AR1420",
                            Origen = "AEP (Buenos Aires)"
                        },
                        new
                        {
                            Id = 3,
                            AeronaveId = 2,
                            Destino = "FTE (El Calafate)",
                            Estado = "Programado",
                            FechaHoraLlegada = new DateTime(2026, 6, 2, 13, 35, 0, 0, DateTimeKind.Local),
                            FechaHoraSalida = new DateTime(2026, 6, 2, 10, 15, 0, 0, DateTimeKind.Local),
                            NumeroVuelo = "AR1844",
                            Origen = "AEP (Buenos Aires)"
                        });
                });

            modelBuilder.Entity("despachoAeronave.Models.Despacho", b =>
                {
                    b.HasOne("despachoAeronave.Models.Vuelo", "Vuelo")
                        .WithMany()
                        .HasForeignKey("VueloId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Vuelo");
                });

            modelBuilder.Entity("despachoAeronave.Models.Vuelo", b =>
                {
                    b.HasOne("despachoAeronave.Models.Aeronave", "Aeronave")
                        .WithMany()
                        .HasForeignKey("AeronaveId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Aeronave");
                });
#pragma warning restore 612, 618
        }
    }
}
